platform :ios, '11.0'
use_modular_headers!
target "GoodBiology" do
pod 'GoogleSignIn'
pod 'lottie-ios'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Google-Mobile-Ads-SDK'
pod 'RealmSwift'
pod 'NewPopMenu'
pod 'Charts'
pod 'Macaw'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'FirebaseUI/Auth'
pod 'Signals'
pod 'SwiftEntryKit'
pod 'WhatsNewKit'
pod 'NotificationBannerSwift'
end
